// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oAlLJzcoNQ1ELHkp-gM4CQV6stcE7Kg',
    appId: '1:1069285788643:web:3372a7c5ec716ca3826ed6',
    messagingSenderId: '1069285788643',
    projectId: 'grocery-task-maximsqrt',
    authDomain: 'grocery-task-maximsqrt.firebaseapp.com',
    storageBucket: 'grocery-task-maximsqrt.appspot.com',
    measurementId: 'G-VS4R16RF4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH83gpqYd-M2weVhJAbmuBUzJTZSqGDtA',
    appId: '1:1069285788643:android:1b2396c7be87acde826ed6',
    messagingSenderId: '1069285788643',
    projectId: 'grocery-task-maximsqrt',
    storageBucket: 'grocery-task-maximsqrt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKpqDEvjY5GyL5hC8CKq_xMSW0BCFXk10',
    appId: '1:1069285788643:ios:26ef0b823e18cd60826ed6',
    messagingSenderId: '1069285788643',
    projectId: 'grocery-task-maximsqrt',
    storageBucket: 'grocery-task-maximsqrt.appspot.com',
    iosBundleId: 'com.example.groceryTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKpqDEvjY5GyL5hC8CKq_xMSW0BCFXk10',
    appId: '1:1069285788643:ios:c41be9cc073b48a5826ed6',
    messagingSenderId: '1069285788643',
    projectId: 'grocery-task-maximsqrt',
    storageBucket: 'grocery-task-maximsqrt.appspot.com',
    iosBundleId: 'com.example.groceryTask.RunnerTests',
  );
}
